title: Monos
email: badnewschoi@gmail.com
description: record is money💸
github_username: choiseonjae
highlighter: rouge
svg:
  optimize: true
highlighter-theme: monokai
date_format: '%Y-%M-%D'
plugins:
  - jekyll-feed
category_dir: category/
tag_dir: tag/
